CREATE  TABLE `RUNNING_JOBFLOWS` (
  `JOBFLOW_SID` BIGINT NOT NULL  AUTO_INCREMENT,
  `BATCH_ID` VARCHAR(128) NOT NULL ,
  `JOBFLOW_ID` VARCHAR(128) NOT NULL ,
  `TARGET_NAME` VARCHAR(128) NOT NULL ,
  `EXECUTION_ID` VARCHAR(128) NOT NULL ,
  `EXPECTED_COMPLETION_DATETIME` DATETIME NOT NULL ,
  PRIMARY KEY (`JOBFLOW_SID`) ) ENGINE=InnoDB;

CREATE  TABLE `JOBFLOW_INSTANCE_LOCK` (
  `EXECUTION_ID` VARCHAR(128) NOT NULL ,
  PRIMARY KEY (`EXECUTION_ID`) ) ENGINE=InnoDB;

CREATE  TABLE `IMPORT_TABLE_LOCK` (
  `TABLE_NAME` VARCHAR(64) NOT NULL ,
  `JOBFLOW_SID` BIGINT NULL ,
  PRIMARY KEY (`TABLE_NAME`) ) ENGINE=InnoDB;

CREATE  TABLE `IMPORT_RECORD_LOCK` (
  `JOBFLOW_SID` BIGINT NOT NULL ,
  `TABLE_NAME` VARCHAR(64) NOT NULL ,
  PRIMARY KEY (`JOBFLOW_SID`, `TABLE_NAME`)) ENGINE=InnoDB;

CREATE  TABLE `EXPORT_TEMP_TABLE` (
  `JOBFLOW_SID` BIGINT NOT NULL ,
  `TABLE_NAME` VARCHAR(64) NOT NULL ,
  `EXPORT_TEMP_SEQ` BIGINT NOT NULL  AUTO_INCREMENT,
  `EXPORT_TEMP_NAME` VARCHAR(64) NULL ,
  `DUPLICATE_FLG_NAME` VARCHAR(64) NULL ,
  `TEMP_TABLE_STATUS` CHAR(1) NULL ,
  PRIMARY KEY (`JOBFLOW_SID`, `TABLE_NAME`),
  INDEX I_EXPORT_TEMP_SEQ (EXPORT_TEMP_SEQ)) ENGINE=InnoDB;

CREATE  TABLE __TG_CACHE_INFO (
    CACHE_ID VARCHAR(128) NOT NULL,
    CACHE_TIMESTAMP DATETIME NOT NULL,
    BUILT_TIMESTAMP DATETIME NOT NULL,
    TABLE_NAME VARCHAR(64) NOT NULL,
    REMOTE_PATH VARCHAR(255) NOT NULL,
    ACTIVE BOOL NOT NULL,
    PRIMARY KEY (CACHE_ID),
    INDEX I_CACHE_INFO_TABLE_NAME (TABLE_NAME)
) ENGINE=InnoDB;

CREATE  TABLE __TG_CACHE_LOCK (
    CACHE_ID VARCHAR(128) NOT NULL,
    EXECUTION_ID VARCHAR(128) NOT NULL,
    ACQUIRED DATETIME NOT NULL,
    PRIMARY KEY (CACHE_ID),
    INDEX I_CACHE_LOCK_EXECUTION_ID (EXECUTION_ID)
) ENGINE=InnoDB;
