DROP TABLE IF EXISTS EXPORT_TEMP_TABLE;
DROP TABLE IF EXISTS IMPORT_RECORD_LOCK;
DROP TABLE IF EXISTS IMPORT_TABLE_LOCK;
DROP TABLE IF EXISTS JOBFLOW_INSTANCE_LOCK;
DROP TABLE IF EXISTS RUNNING_JOBFLOWS;
DROP TABLE IF EXISTS __TG_CACHE_INFO;
DROP TABLE IF EXISTS __TG_CACHE_LOCK;
