CREATE TABLE TYPES(
    ORDINAL INT AUTO_INCREMENT,
    C_INT INT,
    C_TEXT VARCHAR(100),
    C_BOOLEAN BOOL,
    C_BYTE TINYINT,
    C_SHORT SMALLINT,
    C_LONG BIGINT,
    C_FLOAT FLOAT,
    C_DOUBLE DOUBLE,
    C_DECIMAL DECIMAL(10, 4),
    C_DATE DATE,
    C_DATETIME TIMESTAMP
);
