DROP TABLE IF EXISTS @TABLE_NAME@_RL;
CREATE TABLE @TABLE_NAME@_RL (
  SID BIGINT PRIMARY KEY ,
  JOBFLOW_SID BIGINT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS @TABLE_NAME@_RC;
CREATE TABLE @TABLE_NAME@_RC (
  SID BIGINT PRIMARY KEY ,
  CACHE_FILE_SID VARCHAR(45) NULL ,
  CREATE_DATE DATETIME NULL
) ENGINE=InnoDB;

