CREATE TABLE DUP_CHECK(
    NUMBER INT,
    TEXT VARCHAR(100),
    C_BOOL BOOL,
    C_BYTE TINYINT,
    C_SHORT SMALLINT,
    C_LONG BIGINT,
    C_FLOAT FLOAT,
    C_DOUBLE DOUBLE,
    C_DECIMAL DECIMAL(10, 2),
    C_DATE DATE,
    C_TIME TIME,
    C_DATETIME TIMESTAMP
);
