DROP TABLE IF EXISTS EX1;
DROP TABLE IF EXISTS EX2;
DROP VIEW IF EXISTS EX_JOINED;
DROP VIEW IF EXISTS EX_SUMMARIZED;

CREATE TABLE EX1 (
  SID BIGINT AUTO_INCREMENT,
  VALUE  INT                   NULL,
  STRING VARCHAR(255)          NULL,
  VERSION_NO BIGINT            NULL,
  RGST_DATETIME DATETIME       NULL,
  UPDT_DATETIME DATETIME       NULL,
  DELETE_FLAG CHAR(1)          NULL,
  PRIMARY KEY (SID) ) ENGINE=InnoDB;
  
CREATE TABLE EX2 (
  SID BIGINT AUTO_INCREMENT,
  VALUE  INT                   NULL,
  STRING VARCHAR(255)          NULL,
  VERSION_NO BIGINT            NULL,
  RGST_DATETIME DATETIME       NULL,
  UPDT_DATETIME DATETIME       NULL,
  DELETE_FLAG CHAR(1)          NULL,
  PRIMARY KEY (SID) ) ENGINE=InnoDB;

CREATE VIEW EX_JOINED AS
SELECT
    EX1.SID AS SID1,
    EX2.SID AS SID2,
    EX1.VALUE AS VALUE
FROM EX1
JOIN EX2
WHERE
    EX1.VALUE = EX2.VALUE;

CREATE VIEW EX_SUMMARIZED AS
SELECT
    STRING     AS STRING,
    SUM(VALUE) AS VALUE,
    COUNT(SID) AS count
FROM EX1
GROUP BY STRING;
