DROP TABLE IF EXISTS IMPORT_TARGET1;
DROP TABLE IF EXISTS IMPORT_TARGET2;

CREATE  TABLE `IMPORT_TARGET1` (
  `SID` INT NOT NULL  AUTO_INCREMENT,
  `TEXTDATA1` VARCHAR(45) NULL ,
  `INTDATA1` INT NULL ,
  `DATEDATA1` DATETIME NULL ,
  `LAST_UPDATE_TIME` TIMESTAMP NULL ,
  `JOBFLOW_SID` INT NULL ,
  `CACHE_FILE_SID` VARCHAR(45) NULL ,
  PRIMARY KEY (`SID`) ) ENGINE=InnoDB;

CREATE  TABLE `IMPORT_TARGET2` (
  `SID` INT NOT NULL  AUTO_INCREMENT,
  `TEXTDATA2` VARCHAR(45) NULL ,
  `INTDATA2` INT NULL ,
  `DATEDATA2` DATETIME NULL ,
  `LAST_UPDATE_TIME` TIMESTAMP NULL ,
  `JOBFLOW_SID` INT NULL ,
  `CACHE_FILE_SID` VARCHAR(45) NULL ,
  PRIMARY KEY (`SID`) ) ENGINE=InnoDB;